name: Firebase Hosting Deploy

on:
  push:
    branches:
      - main  # deploy only from main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build Vue app
        run: npm run build
        env:
          VITE_FIREBASE_API_KEY: ${{ secrets.VITE_FIREBASE_API_KEY }}
          VITE_FIREBASE_AUTH_DOMAIN: ${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}
          VITE_FIREBASE_PROJECT_ID: ${{ secrets.VITE_FIREBASE_PROJECT_ID }}
          VITE_FIREBASE_STORAGE_BUCKET: ${{ secrets.VITE_FIREBASE_STORAGE_BUCKET }}
          VITE_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }}
          VITE_FIREBASE_APP_ID: ${{ secrets.VITE_FIREBASE_APP_ID }}
          VITE_GEMINI_API_KEY: ${{ secrets.VITE_GEMINI_API_KEY }}
          VITE_APP_READ_API_URL: ${{ secrets.VITE_APP_READ_API_URL }}
          VITE_APP_UPDATE_API_URL: ${{ secrets.VITE_APP_UPDATE_API_URL }}
          VITE_PREDICT_URL: ${{ secrets.VITE_PREDICT_URL }}
          VITE_TRAINING_API_URL: ${{ secrets.VITE_TRAINING_API_URL }}
          VITE_CLUSTER_URL: ${{ secrets.VITE_CLUSTER_URL }}
          VITE_FORECAST_URL: ${{ secrets.VITE_FORECAST_URL }}
          VITE_SUSPEND_USER_URL: ${{ secrets.VITE_SUSPEND_USER_URL }}
          VITE_DELETE_USER_URL: ${{ secrets.VITE_DELETE_USER_URL }}
          VITE_ENABLE_USER_URL: ${{ secrets.VITE_ENABLE_USER_URL }}

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          projectId: "energreen-ai-powered-iot-based"
          channelId: "live"
